---
- hosts: slave
  become: true

  tasks:
  - name: install java
    command: amazon-linux-extras install java-openjdk11 -y

  - name: install git, maven and docker
    yum:
      name: [ git, maven, docker ]
      state: installed

  - name: start docker service
    service:
      name: docker
      state: started
